### ISSUE TITLE
rebar3 compatibility

### ISSUE THREAD

**Issue by arashbm** [msantos/procket#22]
when included as a dependency in a rebar3 `rebar.config`, procket C code is not built completely. After `rebar3 compile` there is no `procket.so` in `priv` directory (the only file is executable `procket`)

It seems that a little bit of makefile tweaking is needed for rebar3 to compile build c files. There is are some info about it on [rebar3 documentations on building C/C++](http://www.rebar3.org/v3.0/docs/building-cc). Sounds like you should just put all the implicit build instructions that rebar 2 used in a makefile and call it as a `pre_hook`.

**Comment by arashbm** [comment]
Something along [these lines](https://github.com/msantos/procket/compare/master...arashbm:rebar3) maybe?

**Comment by msantos** [comment]
@arashbm thanks for all the info and for the patch! I've been dreading the move to rebar3 but, after looking at your links, its not so bad. Quick and dirty patch is here:

https://github.com/msantos/procket/compare/rebar3?expand=1

I've only tested on linux. Patch needs some cleanup still. I am also going to remove some of the targets from the main Makefile (like make dialyzer) now that rebar natively supports it.

About your linking issue: easiest way to figure out what is going on is to run "rebar -vv" to see what rebar is doing.

**Comment by arashbm** [comment]
The branch worked great! The only thing is that the priv directory was not created when I added procket as a dependency and build failed because of that:

```
cc -m64 -g -Wall -o /home/arashbm/omg/_build/default/lib/procket/priv/procket -L/home/arashbm/omg/_build/default/lib/procket/c_src procket_cmd.c -lancillary
/usr/bin/ld: cannot open output file /home/arashbm/omg/_build/default/lib/procket/priv/procket: No such file or directory
```

I believe [this line](https://github.com/msantos/procket/compare/rebar3?expand=1#diff-44f2cd15911739471ffda6f032cc7fd8R74) is somehow not doing what it should.
But after I create it by hand (`mkdir _build/default/lib/procket/priv`) everything works great.

**Comment by msantos** [comment]
Thanks! You're right, the target for the procket binary was being called before the priv directory was created. I pushed a fix on the branch.
