### ISSUE TITLE
Example fails on OSX

### ISSUE THREAD

**Issue by philipcristiano** [msantos/procket#26]
Running the example

```
1> {ok, FD} = procket:open(53, [{protocol, udp},{type, dgram},{family, inet}]).
{ok,9}
2> {ok, S} = gen_udp:open(53, [{fd,FD}]).
{ok,#Port<0.929>}
```

seems to give me an error on OSX

```
1> {ok, FD} = procket:open(53, [{protocol, udp},{type, dgram},{family, inet}]).
{ok,14}
2> {ok, S} = gen_udp:open(53, [{fd,FD}]).
** exception error: no match of right hand side value {error,einval}
```

When trying on a variety of ports. Is this expected to work on OSX?

**Comment by msantos** [comment]
@philipcristiano definitely, OSX is a supported platform.

Are the erlang versions the same in the two examples? I think there was a change that required specifiying a port of 0 when passing in an fd. Try doing:
~~~ erlang
{ok, FD} = procket:open(53, [{protocol, udp},{type, dgram},{family, inet}]),
{ok, S} = gen_udp:open(0, [{fd,FD}]).
~~~

**Comment by philipcristiano** [comment]
@msantos ah cheers! That solved it.

```
2> {ok, S} = gen_udp:open(0, [{fd,FD}]).
{ok,#Port<0.4118>}
```

Thanks for the quick support!
