### ISSUE TITLE
Version number issue

### ISSUE THREAD

**Issue by qwertystop** [msantos/procket#30]
The version of this [on Hex](https://hex.pm/packages/procket/0.7.0) is at 0.7.0, `src/procket.app.src` matches that number, but Releases here lists an 0.8.0 (which still has 0.7.0 in the `app.src` version number). Checking what's downloaded from Hex, it is the misnumbered 0.8.0 release, not the original 0.7.0.

(I can't just do a pull request fixing this because I don't have the authority to decide that the commits since that point justify a new release, or to be retroactively included in the old one as seems to have happened with 0.8.0.)

Up to you what to do, but the current situation is inaccurate.

(Related: The README doesn't list changes since 0.04)

**Comment by msantos** [comment]
procket is on hex?!! That is awesome, thank you for letting me know about this problem!

Sorry for the n00b question but how do you think it should be fixed? Will updating src/procket.app.src to 0.8.0 fix the issue?

And apologies this issue popped up in the first place. I've been a little lax with the tagging since most people seem to pull from the commit id.

**Comment by qwertystop** [comment]
Huh. I assumed you had put it on Hex... but no, looking at it, it's  @slashmili who did that.

Just bumping the version number won't do it – I think you'd need to manually update Hex. Since you're not actually listed as the owner on Hex... you might need to get @slashmili to do it? Never actually put something on Hex, myself.

My recommendation would be to update src/procket.app.src to 0.9.0 (since 0.8.0 already happened, even if it was misnumbered, and what has been done since is sufficient to justify a minor rather than patch version number increase), mark that commit as a release, and then either:
- Push it to Hex
- Get @slashmili to push it to Hex
- Get @slashmili to give you ownership of the Hex project (is this possible?), then push it yourself
- Watch Hex automatically update when a new release happens?
As I said, I haven't put anything on Hex before, so I don't know how updating things works, whether it would automatically reference the GitHub release and update itself, or whether an ownership transfer would be required.

Possibly also do a branch off from the 0.8.0 release with a version number correction to 0.8.1, marked also as a release, for accuracy. That's lower-priority, though.

**Comment by msantos** [comment]
Thanks, that makes sense. I'll take a look at this in the next few days.

**Comment by fhunleth** [comment]
I'm very interested in this as well. There are a few good changes since the last release. Would you mind making another release?

@slashmili - would you be willing to update hex.pm with a new release when the time comes?

If @slashmili is not available, I'll look into getting you permission or helping out myself.

**Comment by slashmili** [comment]
Hey, I'm here! Funny that I missed the notification when @qwertystop mentioned me

@msantos please create an account in Hex and I can add you to procket

**Comment by msantos** [comment]
Will do, sorry for being so slow on this one. Account created:
https://hex.pm/users/msantos

@slashmili thanks so much for adding procket to hex.pm!

**Comment by slashmili** [comment]
@msantos thanks for the great library

I've added you https://hex.pm/packages/procket

**Comment by msantos** [comment]
Finally released as 0.9.2 and updated on hex.pm! Please let me know if you run into any problems.
