### ISSUE TITLE
packet: ifindex/2 returns wrong index number once the number goes beyond one byte

### ISSUE THREAD

**Issue by GoelDeepak** [msantos/procket#34]
If the index number is such that it is beyond 1 byte then packet:ifindex will return wrong number. This is happening because of a bug in the code:
{ok, <<_Ifname:16/bytes, **Ifr:8**, _/binary>>} = procket:ioctl(Socket, ....).

**Comment by msantos** [comment]
Fixed in https://github.com/msantos/procket/pull/35
