### ISSUE TITLE
Request: use canonical Maj.Min.Patch form for tagging

### ISSUE THREAD

**Issue by meox** [msantos/procket#55]
Can you tag this lib using the canonical form:
Maj.Min.Patch

example:
0.9.9 instead of v0.9.9

thanks

**Comment by msantos** [comment]
@meox the hex convention defaults to prefix tags with a `v`. For the ex_docs plugin, it looks like it is configurable now: https://github.com/starbelly/rebar3_ex_doc/issues/18
